availability_zones       = ["us-east-1a", "us-east-1b"]
cluster_name             = "ecs-cluster"
key_name                 = "N.virginia-key"
vpc_cidr_block           = "10.0.0.0/16"
public_subnet_cidrs      = ["10.0.1.0/24", "10.0.2.0/24"]
nodejs_task_definition   = "nodejs-task"
mongodb_task_definition  = "mongodb-task"
prometheus_task_definition = "prometheus-task"
grafana_task_definition    = "grafana-task"
