global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nodejs'
    metrics_path: /metrics
    static_configs:
      - targets: ['nodejs:3000']


  - job_name: 'mongodb'
    metrics_path: /metrics
    static_configs:
      - targets: ['mongodb-service:27017']
